/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mozy_mobile_android_security_SyzygyVbiAPI */

#ifndef _Included_com_mozy_mobile_android_security_SyzygyVbiAPI
#define _Included_com_mozy_mobile_android_security_SyzygyVbiAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mozy_mobile_android_security_SyzygyVbiAPI
 * Method:    restore
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mozy_mobile_android_security_SyzygyVbiAPI_restore
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif

